
db:
  DriverName: "mysql"
  Database: "vision_cloud_test"
  Port: "3306"
  UserName: "sams_test"
  Password: "$1qaz2wsx$"
  Host: "rm-2ze9584p1u9q7tq5svo.mysql.rds.aliyuncs.com"
  Charset: "utf8mb4"

log:
  LogDir: "C:/YUSS/mywork/code/golang/src/GolangStudy/blog/blog.log"
  LogLevel: "info"

jwt:
  Secret: "blog_secret"
  TokenExpire: 24
  Issuer: "yuss"